from enum import IntEnum, Enum


class Colour(IntEnum):
    BLACK = 0
    WHITE = 1


class FontType(Enum):
    TTF = "ttf"
    OTF = "otf"
    BITMAP = "bitmap"



SSD1305_I2C_ADDRESS = 0x3C


# SSD1305 command constants
SET_LOW_COLUMN = 0x00
SET_HIGH_COLUMN = 0x10
SET_MEMORY_MODE = 0x20
SET_COLUMN_ADDRESS = 0x21
SET_PAGE_ADDRESS = 0x22
SET_START_LINE = 0x40

SET_CONTRAST = 0x81
SET_BRIGHTNESS = 0x82

SET_LUT = 0x91

SEGMENT_REMAP = 0xA0
DISPLAY_ALL_ON_RESUME = 0xA4
NORMAL_DISPLAY = 0xA6
INVERT_DISPLAY = 0xA7  # Inverted display colour
SET_MULTIPLEX = 0xA8
DISPLAY_DIM = 0xAC
MASTER_CONFIG = 0xAD
DISPLAY_OFF = 0xAE
DISPLAY_ON = 0xAF

SET_PAGE_START = 0xB0

COM_SCAN_INC = 0xC0
COM_SCAN_DEC = 0xC8
SET_DISPLAY_OFFSET = 0xD3
SET_DISPLAY_CLOCK_DIV = 0xD5
SET_AREA_COLOUR = 0xD8
SET_PRECHARGE = 0xD9
SET_COM_PIN_CFG = 0xDA
SET_VCOM_LEVEL = 0xDB
SET_CHARGE_PUMP = 0x8D
